name: Check MyLink Code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  html-validation:
    name: Validate HTML5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          # Na versão v7+, usamos 'extra' para passar argumentos adicionais como extensões
          extra: --match *.html
          # Ignora erros de scripts externos se necessário
          ignore_re: 'https://cdn.tailwindcss.com'
